service: grocerylist-api

provider:
    name: aws
    runtime: nodejs8.10
    environment:
        DYNAMODB_TABLE: ${self:service}-db-${self:provider.stage}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
    query:
        handler: handler.query
        events:
            - http:
                  path: query
                  method: get
            - http:
                  path: query
                  method: post

resources:
    Resources:
        GroceryListsTable:
            Type: "AWS::DynamoDB::Table"
            Properties:
                AttributeDefinitions:
                    - AttributeName: listId
                      AttributeType: S
                KeySchema:
                    - AttributeName: listId
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: ${self:provider.environment.DYNAMODB_TABLE}
